(function (root, factory) {
  const value = factory();
  if (typeof module === "object" && module.exports) module.exports = value;
  else root.AUDIT = value;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const dimensions = ["Methodology", "Reproducibility", "Leakage control", "Evaluation", "Implementation"];
  const projects = [
    {id:"00",name:"Dynamic Todo Workspace",type:"Software / non-DS",score:54,status:"Limited assurance",scores:[20,62,50,25,82],strength:"Clean dependency-free implementation with explicit local-only storage.",verdict:"Not a data-science system; DS dimensions are not applicable and automated coverage is absent.",findings:[
      ["medium","No automated tests","The README relies on manual browser checks; persistence, filtering, and date logic have no regression suite.","00_dynamic_todo_workspace/README.md"],
      ["info","Out of DS scope","No model, dataset, metric, or inference claim exists, so leakage and statistical evaluation cannot be meaningfully assessed.","00_dynamic_todo_workspace/app.js"]]},
    {id:"01",name:"NYC Taxi Trip Prediction",type:"Supervised regression",score:60,status:"Needs controls",scores:[54,78,74,43,72],strength:"Deterministic feature generation, baseline MAE, persisted bundle, and API validation are solid teaching practices.",verdict:"The shipped 0.980 R² is an in-distribution synthetic recovery result, not evidence of NYC generalization.",findings:[
      ["high","Synthetic target makes the headline metric optimistic","Default labels are generated directly from distance, hour, and noise; the model is evaluated on the same generator family.","01_nyc_taxi_trip_prediction/model.py:37"],
      ["medium","Random split ignores temporal and spatial drift","A single random 80/20 split cannot test later months, neighborhood shift, or repeated route dependence.","01_nyc_taxi_trip_prediction/model.py:83"],
      ["medium","No uncertainty or subgroup error analysis","MAE, RMSLE, and R² are point estimates with no confidence interval, worst-slice, or calibration analysis.","01_nyc_taxi_trip_prediction/model.py:91"]]},
    {id:"02",name:"Nano LLM Transformer",type:"Language model",score:52,status:"High risk",scores:[47,75,58,32,70],strength:"Modern compact architecture, deterministic seeds, dialogue-boundary split, and explicit limitation language.",verdict:"The saved checkpoint is materially overfit: validation loss rises from about 4.38 at step 200 to 5.65 at step 1,200 while train loss falls to 0.047.",findings:[
      ["critical","Final checkpoint is far past the validation optimum","Training always saves the last model; there is no best-checkpoint retention or early stopping despite a clear validation reversal.","02_nano_llm_transformer/train.py:133"],
      ["high","Tokenizer vocabulary sees validation text","WordTokenizer.fit receives the full raw corpus before the split, leaking validation vocabulary into representation design.","02_nano_llm_transformer/train.py:42"],
      ["high","Evaluation is too narrow for chatbot quality","Five random loss batches and perplexity on 239 tokens do not measure response relevance, memorization, diversity, or safety.","02_nano_llm_transformer/train.py:52"],
      ["medium","Device determinism is incomplete","Seeds are set, but deterministic algorithms and backend settings are not enforced across CUDA/MPS.","02_nano_llm_transformer/train.py:22"]]},
    {id:"03",name:"Customer Segmentation Clustering",type:"Unsupervised learning",score:65,status:"Needs controls",scores:[67,84,68,50,69],strength:"Broad 48-configuration audit, multiple internal indices, bootstrap ARI, fixed seed, and strong input contracts.",verdict:"Useful exploratory segmentation, but the winning six-cluster solution is selected and characterized on the same 200 customers.",findings:[
      ["high","Selection and reporting reuse the full sample","Scaler, candidate selection, stability, profiles, and PCA all use the same small dataset; no external or held-out stability check exists.","03_customer_segmentation_clustering/model.py:71"],
      ["medium","Composite objective is not validated","The 55/35/10 weighting and DB cap are hand-set; rankings may change under plausible weights.","03_customer_segmentation_clustering/model.py:98"],
      ["medium","Deployment contract breaks for agglomerative winners","The search can select AgglomerativeClustering, which has no predict method for new customers, yet it is persisted as a model bundle.","03_customer_segmentation_clustering/model.py:138"]]},
    {id:"04",name:"Associative Pattern Mining",type:"Association rules",score:61,status:"Needs controls",scores:[60,82,55,42,68],strength:"Correct member-day basket grain, deduplication, Apriori pruning, deterministic exhaustive grid audit, and multiple rule metrics.",verdict:"The rule engine is reproducible, but threshold optimization maximizes an in-sample heuristic and does not validate rule persistence.",findings:[
      ["high","Rules and thresholds are optimized on the same baskets","All 250 configurations and the final rules reuse one full snapshot; there is no temporal/member holdout.","04_associative_pattern_mining/model.py:119"],
      ["high","Multiple-testing risk is uncontrolled","Hundreds of candidate itemsets are screened without false-discovery control or resampling confidence intervals.","04_associative_pattern_mining/model.py:60"],
      ["medium","Coverage objective double-count correction is heuristic","Summed directional supports divided by two does not generally yield unique transaction coverage.","04_associative_pattern_mining/model.py:91"]]},
    {id:"05",name:"Data Science Skills Lab",type:"Multi-method teaching lab",score:79,status:"Good teaching assurance",scores:[78,88,88,72,71],strength:"Leakage-safe sklearn pipeline, nested preprocessing within CV, untouched test split, hashes, SQL reconciliation, and explicit causal guardrails.",verdict:"Strong educational spine; breadth is demonstrated mainly through generated narrative artifacts rather than executing every advertised technique.",findings:[
      ["medium","Many skill demonstrations are templated evidence","skill_evidence maps name keywords to shared facts; it does not execute 46 independent analytical workflows.","05_data_science_skills_lab/lab.py:119"],
      ["medium","One split limits precision","The final ROC-AUC is from one 223-row holdout with no interval or repeated nested CV.","05_data_science_skills_lab/lab.py:67"],
      ["low","Retrieval demo embeds the answer in documents and query","It is a contract smoke test, not a meaningful retrieval benchmark with relevance judgments.","05_data_science_skills_lab/lab.py:94"]]},
    {id:"06",name:"Anomaly Detection",type:"Semi-supervised anomaly detection",score:86,status:"Strongest assurance",scores:[88,90,91,84,77],strength:"Normal-only fit, stratified train/validation/holdout, validation-only search and thresholding, PR-AUC emphasis, alert budget, stability, and persisted scored holdout.",verdict:"The portfolio has the strongest evaluation separation in Part 2, though uncertainty and deployment drift checks remain missing.",findings:[
      ["medium","No uncertainty around holdout metrics","PR-AUC, precision, and recall are single-split point estimates despite only about 107 holdout anomalies.","06_anomaly_detection/model.py:139"],
      ["medium","Threshold does not enforce the claimed alert budget exactly","A validation quantile can produce a different holdout alert rate under drift; capacity calibration is not bounded statistically.","06_anomaly_detection/model.py:146"],
      ["low","Clinical benchmark shift is not tested","A random split of a pooled benchmark does not simulate site, time, device, or population drift.","06_anomaly_detection/model.py:37"]]},
    {id:"07",name:"AutoML AutoGluon",type:"AutoML portfolio",score:82,status:"Good teaching assurance",scores:[83,81,92,78,76],strength:"Separate train/validation/test sets, validation-only candidate acceptance, task-appropriate metrics, budgets, inference checks, and real persisted predictors.",verdict:"Methodologically sound for compact demos; small holdouts and a partially uncontrolled AutoML seed prevent stronger claims.",findings:[
      ["medium","AutoGluon training seed is not pinned","Dataset splits are seeded, but predictor fit does not pass random_seed; exact models can vary by version and runtime.","07_automl_autogluon/model.py:82"],
      ["medium","Tiny test sets make scores unstable","Iris accuracy is based on 30 records and breast-cancer metrics on 114, with no confidence intervals.","07_automl_autogluon/model.py:55"],
      ["low","Latency estimate is a warm, tiny-batch microbenchmark","One prediction call divided by row count omits cold start, distribution, serialization, and concurrency.","07_automl_autogluon/model.py:60"]]},
    {id:"08",name:"Data Science Visual Mastery",type:"Interactive curriculum",score:58,status:"Limited assurance",scores:[58,70,50,45,67],strength:"Dependency-free simulations make priors, thresholds, derivatives, and backpropagation tangible and accessible.",verdict:"Educational content is interactive but lacks automated correctness tests for formulas, simulations, quizzes, and accessibility behavior.",findings:[
      ["high","No executable correctness suite","README validation is syntax plus manual interaction; numerical invariants and quiz scoring can regress silently.","08_datascience_visual_mastery/README.md"],
      ["medium","Simulations do not communicate sampling uncertainty","Interactive point results can look definitive without repeated-sample variability or interval framing.","08_datascience_visual_mastery/app.js"],
      ["medium","No learning evaluation","Quiz completion is not evidence that the curriculum improves understanding; no pre/post or item analysis exists.","08_datascience_visual_mastery/index.html"]]},
    {id:"09",name:"FlowForge DAG Engine",type:"Data engineering / non-model",score:76,status:"Strong software assurance",scores:[63,85,88,68,90],strength:"Deep DAG module, stable planning, failure propagation, persistence, API lifecycle tests, browser-logic tests, and explicit specification.",verdict:"Excellent software testing for orchestration; scientific lineage, dataset versioning, and experiment reproducibility are outside its current contract.",findings:[
      ["medium","Runs lack data/artifact lineage guarantees","The local engine stores workflow state but does not hash inputs, code, environment, or output schemas for reproducible DS runs.","09_flowforge_dag_engine/flowforge/repository.py"],
      ["medium","No concurrency or retry semantics","Deterministic local execution is tested, but production failure recovery and idempotence are not modeled.","09_flowforge_dag_engine/flowforge/engine.py"],
      ["low","Node validation is intentionally narrow","Five demo node types provide a clean seam, not a general data-pipeline validation framework.","09_flowforge_dag_engine/docs/spec.md"]]},
    {id:"10",name:"CRISP-DM Masters Curriculum",type:"Multi-method DS curriculum",score:68,status:"Needs controls",scores:[70,82,72,55,63],strength:"Leakage-safe supervised preprocessing, stratified split, deterministic workflows, explicit association caveats, and broad functional tests.",verdict:"Broad and reproducible as teaching code, but most workflows use the full dataset and the supervised comparison reuses one holdout for model choice.",findings:[
      ["high","Test holdout selects the reported best classifier","Two models are compared on the same test split and the higher ROC-AUC is named best; repeated use turns the test into selection data.","10_crispdm_masters_curriculum/crispdm/pipeline.py:110"],
      ["high","Unsupervised choices are in-sample","K selection, anomaly fitting/ranking, association discovery, and LSH demonstration all reuse the full 891-row dataset.","10_crispdm_masters_curriculum/crispdm/pipeline.py:57"],
      ["medium","Anomaly score transforms data twice","StandardScaler is fit separately for fit_predict and score_samples; equal input makes it deterministic, but reusing one fitted transform would be safer and auditable.","10_crispdm_masters_curriculum/crispdm/pipeline.py:85"],
      ["medium","LSH reports reduction but not retrieval quality","One query has no brute-force recall@k comparison, collision sensitivity, or parameter sweep.","10_crispdm_masters_curriculum/crispdm/pipeline.py:176"]]}
  ];
  return {version:"1.0", audited:"2026-09-01", dimensions, projects, rubric:{scale:"0–100",bands:[[85,"Strong"],[75,"Good"],[60,"Needs controls"],[0,"High risk"]],weights:[20,20,20,20,20],note:"Scores are structured reviewer judgments, not statistically estimated probabilities. Non-DS projects are scored on analogous assurance controls and explicitly marked."}};
});
